server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/Maulid-Abdullahi/config-server
          clone-on-start: true
